[2025-03-27T11:05:13.132+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T11:05:13.177+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_warehouse.load_dim_time_control_dw manual__2025-03-12T14:13:58.419334+00:00 [queued]>
[2025-03-27T11:05:13.208+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_warehouse.load_dim_time_control_dw manual__2025-03-12T14:13:58.419334+00:00 [queued]>
[2025-03-27T11:05:13.210+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-27T11:05:13.251+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_dim_time_control_dw> on 2025-03-12 14:13:58.419334+00:00
[2025-03-27T11:05:13.275+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5304) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-27T11:05:13.280+0000] {standard_task_runner.py:72} INFO - Started process 5324 to run task
[2025-03-27T11:05:13.279+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_data_warehouse', 'load_dim_time_control_dw', 'manual__2025-03-12T14:13:58.419334+00:00', '--job-id', '804', '--raw', '--subdir', 'DAGS_FOLDER/load_data_warehouse_dag.py', '--cfg-path', '/tmp/tmpasijpiig']
[2025-03-27T11:05:13.290+0000] {standard_task_runner.py:105} INFO - Job 804: Subtask load_dim_time_control_dw
[2025-03-27T11:05:13.421+0000] {task_command.py:467} INFO - Running <TaskInstance: load_data_warehouse.load_dim_time_control_dw manual__2025-03-12T14:13:58.419334+00:00 [running]> on host 8de4e0a4beb2
[2025-03-27T11:05:13.636+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_warehouse' AIRFLOW_CTX_TASK_ID='load_dim_time_control_dw' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T14:13:58.419334+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T14:13:58.419334+00:00'
[2025-03-27T11:05:13.641+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-27T11:05:17.621+0000] {logging_mixin.py:190} INFO - âœ… gold/dim_time_control.parquet Loaded: 4 rows, 2 columns
[2025-03-27T11:05:17.687+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_dw'
[2025-03-27T11:05:17.807+0000] {base.py:84} INFO - Retrieving connection 'azure_chess_dw'
[2025-03-27T11:05:31.037+0000] {logging_mixin.py:190} INFO - Successfully Loaded gold/dim_time_control.parquet Data to Postgres table dim_time_control
[2025-03-27T11:05:31.046+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-27T11:05:31.087+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-27T11:05:31.088+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_data_warehouse, task_id=load_dim_time_control_dw, run_id=manual__2025-03-12T14:13:58.419334+00:00, execution_date=20250312T141358, start_date=20250327T110513, end_date=20250327T110531
[2025-03-27T11:05:31.138+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-27T11:05:31.197+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T11:05:31.211+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
